### ISSUE TITLE
Issue with paddingY ( need bottom margin)

### ISSUE THREAD

**Issue by qu4sar** [kciter/Floaty#103]
Hi , i have a UITabBarController and the fab go over the bottom tabbar.
I've setted the value of **paddingY** and the fab's position is ok. 
My problem is that if i press under the fab ( on the itembar ) the fab opens.

**Comment by TeeshaTechnology** [comment]
Hello, I faced same problem,
i was used self.tabBarController?.view.addSubview(fab) and that replaced with self.view.addSubview(fab) and it's work perfectly.

**Comment by soheilnikbin** [comment]
Try to use this code:

`KCFABManager.defaultInstance().getButton().paddingY = 60`

**Comment by psredzinski** [comment]
friendlyTap = false

**Comment by fukemy** [comment]
@psredzinski  ??
