### ISSUE TITLE
Memory leak when vc disappear but FAB have any item.

### ISSUE THREAD

**Issue by chawatvish** [kciter/Floaty#106]
I have a problem about when I back to root view (navigation->pop).
The FAB is stuck in memory like this(I attach image below.)

#FYI 
My Sol. I have to remove FAB Item from FAB before I pop the VC.

Best, Regards

When memory leak

![screen shot 2560-04-02 at 2 00 14 pm](https://cloud.githubusercontent.com/assets/6084987/24585183/5cd170bc-17ae-11e7-93b3-ca2e6a96dcf8.png)

My solution.

![screen shot 2560-04-02 at 2 07 05 pm](https://cloud.githubusercontent.com/assets/6084987/24585176/1359a67a-17ae-11e7-8dcd-35b9b33397b5.png)

**Comment by kciter** [comment]
Closing too old issue.
