### ISSUE TITLE
FAB shows up below screen on TableView even when using "Sticky" property

### ISSUE THREAD

**Issue by eagi223** [kciter/Floaty#107]
Xcode 8.2.1
Installed using CocoaPods
iPhone 6 running iOS 10

Details: This is using the sticky property as true. The floating action button initially begins below the view, though you can see the top of it. When you swipe up (to scroll down) the FAB snaps up to the correct position and then acts correctly.

![img_2817](https://cloud.githubusercontent.com/assets/17199101/24889122/36ae81fc-1e36-11e7-98f2-da5b52d5ac3c.PNG)
![img_2818](https://cloud.githubusercontent.com/assets/17199101/24889123/36bebeaa-1e36-11e7-959a-0a94ad0d6865.PNG)

**Comment by kiranruth** [comment]
Is there a fix for this ?

**Comment by NameX44** [comment]
same problem in UITableViewController

**Comment by kiranruth** [comment]
I found that setting the frame for the floaty and then setting sticky to true solves it.

```
var addButton = Floaty(frame: CGRect(x: 0, y: 0, width: 56, height: 56))
addButton.sticky = true
```

**Comment by dinobei** [comment]
@kiranruth 
In my case, I added `Floaty` to the table view.
If I apply the above solution, the problem with this issue will be resolved, but when I scroll while the `Floaty` is open, the layout in the + button will change. Scrolling the tableview again will recover.

![img_9396](https://user-images.githubusercontent.com/7797499/32090129-e17fdcfe-bb28-11e7-9434-673e7c8c6777.PNG)
![img_9397](https://user-images.githubusercontent.com/7797499/32090112-c2bb5096-bb28-11e7-88b8-d59750d0c128.PNG)

**Comment by giofid** [comment]
I have the same problem and @kiranruth hint solves it. Anyway, I think there is still a bug in **Floaty** because it should be indifferent create a floaty with
`let floaty = Floaty()`
and create it with
`let floaty = Floaty(frame: CGRect(x: 0, y: 0, width: 56, height: 56))`
