### ISSUE TITLE
Action on FAB click

### ISSUE THREAD

**Issue by jcaruso001** [kciter/Floaty#108]
I don't want to have any items attached to the FAB and I want to open another viewcontroller. I have done that with the items on other pages but I cannot with the FAB.

Can someone help?

**Comment by yurish** [comment]
If you are using FAB with UIViewController, then you can implement `KCFloatingActionButtonDelegate` and use 

 `func emptyKCFABSelected(_ fab: KCFloatingActionButton)`

**Comment by computerjulian** [comment]
Just in addition, this function is now named emptyFloatySelected

**Comment by vitalii-tym** [comment]
When I had to automatically trigger the action if there was only 1 item in the button I did this:
1) While configuring the button:  `Floaty.global.button.fabDelegate = self`
2) the implementation:
```
extension someClass: FloatyDelegate {
    func floatyOpened(_ floaty: Floaty) {
            if let floatyItem = floaty.items.first, let theHandler = floatyItem.handler {
                theHandler(floatyItem)
                DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 1) {
                    Floaty.global.button.close()
                }
           }
    }
```
