### ISSUE TITLE
how to prevent the icons from being highlighted on getting selected

### ISSUE THREAD

**Issue by alshcompiler** [kciter/Floaty#123]
how to prevent the icons from being highlighted on getting selected , when i click and hold on the items they get a highlighted circular select in and in my case the icons for floaty items are not circular so it looks ugly, Thanks in advance

**Comment by phtoxa** [comment]
i solved that putting the ImageButton again when fab clicked.
self.FAB.buttonImage = #imageLiteral(resourceName: "FABIcon")

**Comment by kciter** [comment]
Closing too old issue.
