### ISSUE TITLE
Disable rotation of the plus button ?

### ISSUE THREAD

**Issue by NameX44** [kciter/Floaty#129]
Hi,

Is it possible to disable rotation of the + button ?

Thanks for your work !

**Comment by NameX44** [comment]
Found it 👍 

fab.rotationDegrees = 0.0

**Comment by Arthur-Guillaume** [comment]
@NameX44 thanks ! 

Maybe this should be added to the readme :-)

**Comment by kciter** [comment]
Closing too old issue.
