### ISSUE TITLE
Dynamic update button background color

### ISSUE THREAD

**Issue by davros1970** [kciter/Floaty#130]
I've found if I need to dynamically update the button background color that the current implementation isn't ideal for me. My use case is to show button items as being enabled/disabled in the popup. Disabled buttons are grayed out.

I found if I remove FloatyItem.itemBackgroundColor and instead update FloatyItem.buttonColor to the following then I can simply update buttonColor at any time. In my use case, I update the colors in FloatyDelegate.floatingActionButtonWillOpen().

`    open var buttonColor: UIColor = UIColor.white {
        didSet {
            circleLayer.backgroundColor = buttonColor.cgColor
        }
    }
`

itemBackgroundColor seems redundant to me. Just curious if there was a reason for the two different background color properties?

BTW, I really like this FAB implementation. Simple and easy to maintain implementation compared to others I've seen. Thx!

**Comment by chickdan** [comment]
Playing around with it, buttonColor changes the color of the main (or plus) button, whereas the itemButtonColor will change the color of the individual items (so you can have a different color per item).

If you are determining which buttons are disabled in a view other than the view where the FAB is displayed (like in settings for example) then you could set those using UserDefaults and change the item colors in the view's viewWillAppear().

**Comment by kciter** [comment]
Closing too old issue.
