### ISSUE TITLE
Size issue when changing buttonImage 

### ISSUE THREAD

**Issue by mwurm93** [kciter/Floaty#131]
Hi! Thanks for this amazing tool.

I'm trying to change the floaty.buttonImage in the handler of one of the items and it looks like the image is not being constrained to the bounds of the button like it is for the item.icon...screen shot and 
![img_0216 copy](https://user-images.githubusercontent.com/6393161/27656623-7e5b8c92-5bfe-11e7-8147-a6d3355abb0c.png)
code below.
placeToStayItem = FloatyItem()
        placeToStayItem?.buttonColor = UIColor.flatSunFlower()
        placeToStayItem?.title = "Place to stay"
        placeToStayItem?.icon = UIImage(named: "changeHotel")
        placeToStayItem?.handler = { item in
            self.spawnDoYouKnowWhereYouWillBeStayingQuestionView()
            self.floaty?.close()
            self.floaty?.buttonColor = (self.placeToStayItem?.buttonColor)!
            self.floaty?.buttonImage = UIImage(named: "changeHotel")
        }

**Comment by Wndworks** [comment]
You already tried the .size option? `floaty.size = 44`

**Comment by nderkach** [comment]
It seems like the issue is that it ignores item size set in IB.
Works when you set it in the code thought.

**Comment by jrumol** [comment]
I am having the same problem.

Here is my code:

`        let buttonColor = UIColor(red:0.64, green:0.00, blue:0.00, alpha:1.0)
        
        Floaty.global.button.buttonColor = buttonColor
        Floaty.global.button.buttonImage = UIImage(named: "menu")
        
            // First sub-item: Settings.
            let itemSettings = FloatyItem()
            itemSettings.buttonColor = buttonColor
            itemSettings.title = "settings".localized(lang: languageSelected!)
            itemSettings.icon = UIImage(named: "settings")
            itemSettings.handler = { item in
                self.performSegue(withIdentifier: "goToSettings", sender: nil)
            }
            Floaty.global.button.addItem(item: itemSettings)
        
            // Second sub-item: Favourites.
            let itemFavourites = FloatyItem()
            itemFavourites.buttonColor = buttonColor
            itemFavourites.title = "favourites".localized(lang: languageSelected!)
            itemFavourites.icon = UIImage(named: "favourites")
            itemFavourites.handler = { item in
                
            }
            Floaty.global.button.addItem(item: itemFavourites)`

And the result for the "Menu" icon image is the same.

**Comment by kciter** [comment]
Closing too old issue.

**Comment by hamzabinamin** [comment]
@kciter what's the solution to avoid this? I tried setting the size to 44 and it didn't work.

**Comment by preetamjadakar** [comment]
Author chooses to close this issue, without giving a solution or link to a solution if its repeated issue
