### ISSUE TITLE
How to change button background color programmatically

### ISSUE THREAD

**Issue by nodahikaru** [kciter/Floaty#133]
When user taps fab button, I want button background color to be changed. 
How I can change button background color programmatically.
I had used below code

likeBtn.buttonColor = UIColor.init(red: 64/255.0, green: 160.0/255.0, blue: 129/255.0)
but it doesn't work for me.

**Comment by vmax** [comment]
@dl528 
Try calling `setNeedsDisplay` after setting color:

```
likeBtn.buttonColor = UIColor.init(red: 64/255.0, green: 160.0/255.0, blue: 129/255.0)
likeBtn.setNeedsDisplay()
```

**Comment by kciter** [comment]
Closing too old issue.
