### ISSUE TITLE
Floaty Behind UITableView Section Header

### ISSUE THREAD

**Issue by csimmonsbluebook** [kciter/Floaty#137]
When scrolling through a table view, I noticed that the floaty is behind the section headers, as you can see in the image below (I modified the demo app to show it). How can I make sure that the floaty remains completely on top of the table view?

Thanks

![img_0013](https://user-images.githubusercontent.com/19786779/28289694-97b83204-6b11-11e7-858b-4961e900c970.PNG)

**Comment by csimmonsbluebook** [comment]
@kciter With the solution above, the button persists when the navigation stack is pushed. Is there a way to just add the button on top of the entire table view?

**Comment by habosoft** [comment]
Replace your tableviewcontroller with viewcontroller and a tableview inside. Add floaty and it will be above everything.

**Comment by spaquet** [comment]
I recommend adding this to the documentation.
For those interesting it is also working for a TableViewController inside a NavigationViewController.

**Comment by esskar** [comment]
set ZPosition to something big (like 100) when floaty is moved to the super view
