### ISSUE TITLE
Refresh the items list in the button

### ISSUE THREAD

**Issue by vitalii-tym** [kciter/Floaty#139]
In my project I need to refresh the list of items each several seconds. To do this I do the following:

```
Floaty.global.button.close()
Floaty.global.button.items.removeAll()
for item in newItemsList {
      Floaty.global.button.addItem(...)
}
Floaty.global.show()
```
This updates the button contents, but there is a glitch: if the button is open while being refreshed it will be closed. If I don't close the button performing the .show() command while the button is open results in all visible items remaining visible forever.

Is there a better way to refresh already presented button?

**Comment by kciter** [comment]
Closing too old issue.
