### ISSUE TITLE
Feature Request or Is this possible

### ISSUE THREAD

**Issue by wm-j-ray** [kciter/Floaty#141]
I would like to substitute the plus button for the image of the selected menu item. Is this possible?   

I would like to do this using a delegate method to get the index of the selected item rather than using a handler for each menu item.  If I can get floaty.items[index] then I could pull out the name of the image for the selected menu item.

I have looked at the Floaty.swift file and cannot figure out how to get the index of the selected menu item from it.

Any help greatly appreciated and thanx in advance

**Comment by reyhaan** [comment]
Hi Ray,

I think you can do something like this:

`let floaty = Floaty()
 floaty.buttonImage = UIImage(named: "settings")
 floaty.addItem("Freeze", icon: UIImage(named: "freeze"), handler: { item in
            floaty.buttonImage = UIImage(named: "freeze")
            self.toggleFrameFreeze()
})`

**Comment by kciter** [comment]
Closing too old issue.
