### ISSUE TITLE
how to prevent item from toggle the floaty menu

### ISSUE THREAD

**Issue by ebtehalelsaid** [kciter/Floaty#142]
i want to open popover from an item put after showing popover menu closed how to prevent it from closing?

**Comment by Wndworks** [comment]
@ebtehalelsaid 

You could try this: `floaty.autoCloseOnTap = false`

Here are some old options of the previous Floaty version (KCFloatingActionButton): http://cocoadocs.org/docsets/KCFloatingActionButton/1.3.3/Classes/KCFloatingActionButton.html#/s:vC22KCFloatingActionButton22KCFloatingActionButton14autoCloseOnTapSb

**Comment by kciter** [comment]
Closing too old issue.
