### ISSUE TITLE
Update CHANGELOG / add release notes?

### ISSUE THREAD

**Issue by jessesquires** [kciter/Floaty#144]
Hi 👋 

I was trying to see what changed in `3.0.1` and I noticed that the [CHANGELOG](https://github.com/kciter/Floaty/blob/master/CHANGELOG.md) hasn't been updated for quite some time. Release notes are also absent from the [GH releases page](https://github.com/kciter/Floaty/releases).

I think it'd be good practice to try to resume tracking changes. 😄

**Comment by kciter** [comment]
Closing too old issue.
