### ISSUE TITLE
FAB Buttons Off Center (again)

### ISSUE THREAD

**Issue by mattbarker016** [kciter/Floaty#146]
I'm still experiencing this bug using the PopAnimation as seen in Issue #55. I have the button on iPad on the left side on the screen. The images are off too.

<img width="102" alt="messages image 555342164" src="https://user-images.githubusercontent.com/8039928/29856236-7d1e49d0-8d1f-11e7-98cf-6ca848253fb3.png">

**Comment by anuragdake** [comment]
I am also facing the same issue.

**Comment by kciter** [comment]
Closing too old issue.
