### ISSUE TITLE
Floaty doesn't adapt to layout changes when superview is using autolayout

### ISSUE THREAD

**Issue by jjochen** [kciter/Floaty#147]
When Floaty is added to a view which is positioned with autolayout, it doesn't adapt to layout changes (like device rotations)

**Comment by jjochen** [comment]
This is probably because floaty is observing the "frame" of it's superview to adapt to changes. This might not be enough.

**Comment by jjochen** [comment]
Autolayout is setting center and bounds (and not frame) since iOS 8.

**Comment by kciter** [comment]
Thank you!
