### ISSUE TITLE
Swift 4 Support?

### ISSUE THREAD

**Issue by vajahatalee** [kciter/Floaty#153]
Hi,
When are we getting the Swifty update for Swift 4. 
Thanks and Good Work!

**Comment by zoufishanmehdi** [comment]
Same here. Looking forward to Swift 4 update. Thanks for the great work so far :)

**Comment by Natelegreat1** [comment]
> Floaty.swift:810:5: implicit Objective-C entrypoint -[Floaty.Floaty keyboardWillShow:] is deprecated and will be removed in Swift 4; add explicit '@objc' to the declaration to emit the Objective-C entrypoint in Swift 4 and suppress this message

**Comment by jesster2k10** [comment]
Try this:

`pod 'Floaty', :git => 'https://github.com/jesster2k10/Floaty.git', :branch => 'swift4.0'`

**Comment by jesster2k10** [comment]
I created a pull request but you can use that for now until it is merged with the master

**Comment by Natelegreat1** [comment]
I'm getting an error when I try ` pod 'Floaty', '~> 4.0.0'` .. 

`[!] Unable to satisfy the following requirements:

- `Floaty (~> 4.0.0)` required by `Podfile``

**Comment by kciter** [comment]
@Natelegreat1 I just now pod update. Please do it again.
