### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by vikramhimanshu** [kciter/Floaty#155]
I tried integrating this project using pods and it won't work - Xcode 9, Swift

**Comment by vitalii-tym** [comment]
Pods have a problem with Xcode 9 at the moment. Xcode automatically assumes all Pods are written on Swift 4, while Floaty is not converted to Swift 4 yet.
As a workaround try to add this script in the end of your Podfile:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['Floaty'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
```

If you have some other kind of problem, it would be helpful to provide more details about it.

**Comment by kciter** [comment]
Please try `pod 'Floaty', '~> 3.0.0'`. :)

**Comment by gonzalotolaran** [comment]
I am using carthage to integrate it. I am using swift 4.0.
github "kciter/Floaty" ~> 4.0.0
/usr/bin/xcrun xcodebuild -project /Users/gtoledo/Documents/appcode/newivalue/iValue-v1.0/Carthage/Checkouts/Floaty/Floaty.xcodeproj -scheme Floaty -configuration Release -derivedDataPath /Users/gtoledo/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/Floaty/4.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/0w/rbscldpn11n74cwnx698g6gw0000gn/T/Floaty SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/gtoledo/Documents/appcode/newivalue/iValue-v1.0/Carthage/Checkouts/Floaty)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/0w/rbscldpn11n74cwnx698g6gw0000gn/T/carthage-xcodebuild.l0ajan.log

**Comment by kciter** [comment]
Closing too old issue.
