### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by jjochen** [kciter/Floaty#156]
Floaty should take safeAreaInsets into account.

**Comment by kh0r** [comment]
FYI - Fixed it in my fork: https://github.com/kh0r/Floaty/commit/17ed974640deda5b0e886e9aa89929ca97b64b24

**Comment by Natelegreat1** [comment]
When I use `Floaty.global.show(animated)` or `Floaty.global.hide(animated)` it seems to forget about the safeAreaInsets... and - worse! - it registers a click on the X as a click on the first item!! :|

**Comment by kciter** [comment]
Closing too old issue.
