### ISSUE TITLE
rtlMode not available

### ISSUE THREAD

**Issue by JoseVigil** [kciter/Floaty#160]
Hi,

I am trying to set it to the left side of the screen with rtlMode however I cannot access the property. The documentation says:

_Floaty.global.rtlMode = true_

However global (instance of FloatyManager with rtl setter) is not accessible with simple initialization. 

_let floaty = Floaty()_

Any other way of setting it to the left without rtlMode? 

Thanks

pod 'Floaty', '~> 3.0.0'
xCode Version 8.3.3
Swift 3.1

**Comment by kciter** [comment]
try `pod 'Floaty', '~> 4.0.0'`. :)

**Comment by mn288** [comment]
@kciter please close this as it solved the same problem for me

**Comment by JoseVigil** [comment]
Thanks very much! It worked.
