### ISSUE TITLE
RTL Text is mirrored

### ISSUE THREAD

**Issue by mn288** [kciter/Floaty#161]
'**Floaty.global.rtlMode = true**' mirrors even the language when true.
_*Text becomes unreadable_

**Comment by VinsonCai** [comment]
problem still exist. please help

**Comment by asdfghj1237890** [comment]
same problem here too, version ~> 4.1.0

**Comment by kciter** [comment]
Closing too old issue.

**Comment by howard06285** [comment]
Just **change the order of rtlMode command**, 
first  Floaty.global.rtlMode = true, 
then  floaty.addItem("Hello, World!")

```
       let floaty = Floaty()
        floaty.addItem("Hello, World!")
        Floaty.global.rtlMode = true
        self.view.addSubview(floaty)
```
**This above will make text mirrored.** 


```
        let floaty = Floaty()
        Floaty.global.rtlMode = true
        floaty.addItem("Hello, World!")
        self.view.addSubview(floaty)
```
**This works fine.**
