### ISSUE TITLE
Question: When closing, how to ensure items are gone before removing the overlay?

### ISSUE THREAD

**Issue by rodrigolira** [kciter/Floaty#162]
I tried to tweak the demo, looking for a way to only remove the overlay after all items completely disappear.

I tried the most basic approach: I changed the order of statements inside the `close()` method. Sure enough, I noticed I had to add a delay to the overlay removing animation. This seemed straightforwarded.

However, no matter what the number I put on delay, the overlay always disappear before all items are gone.

I tried having my delay calculated as per: `(items.count * animationSpeed) + (items.count * 0.15)` but this didn't work ("0.15" is the duration of the animation for each item to disappear (assuming pop animation is selected). Every item receives a delay of "animationSpeed" aswell.

According to Apple's documentation, duration should be given in seconds. Even if I try something crazy like "20" (seconds) as a parameter, the overlay still end up disappearing before all items are gone (I have 10 items on my sample).

Can anybody help me figure this one out?

Here's a reduced version of the `close()` method (only order of statements is changed):

```
@objc open func close() {
        fabDelegate?.floatyWillClose?(self)
        let animationGroup = DispatchGroup()
        
        if(items.count > 0){
            self.overlayView.removeTarget(self, action: #selector(close), for: UIControlEvents.touchUpInside)        

            switch openAnimationType {
            case .pop:
                popAnimationWithClose(group: animationGroup)
            // other animations removed for readability
            case .none:
                noneAnimationWithClose()
            }

            animationGroup.enter()
            UIView.animate(withDuration: 0.3, delay: 0,
                usingSpringWithDamping: 0.6,
                initialSpringVelocity: 0.8,
                options: [], animations: { () -> Void in
                    self.plusLayer.transform = CATransform3DMakeRotation(self.degreesToRadians(0), 0.0, 0.0, 1.0)
                    self.buttonImageView.transform = CGAffineTransform(rotationAngle: self.degreesToRadians(0))
                    self.overlayView.alpha = 0
                }, completion: {(f) -> Void in
                    if self.overlayViewDidCompleteOpenAnimation {
                        self.overlayView.removeFromSuperview()
                    }
                    animationGroup.leave()
            })
        }

        animationGroup.notify(queue: .main) {
            self.fabDelegate?.floatyDidClose?(self)
        }
        fabDelegate?.floatyClosed?(self)
        closed = true
    }
```

**Comment by kciter** [comment]
Closing too old issue.
