### ISSUE TITLE
XCTest can't find floaty item buttons

### ISSUE THREAD

**Issue by jmilillo** [kciter/Floaty#168]
What is the proper way to automate tests?   I can set accessibility ids on FloatyItems but I can't seem to "find" them in my tests.   They also don't [seem to] appear as descendants of the main Floaty.

I can find the main button with:
`app.otherElements["floaty"].exists`
but not any items:
`app.otherElements["floatyitem"].exists`

if I look at the floaty:
`app.otherElements["floaty"].descendants(matching: .any).count`
I get one element, and it's the image.

**Comment by nderkach** [comment]
You need to set item's label, like this

<img width="295" alt="screen shot 2017-12-24 at 10 24 13 pm" src="https://user-images.githubusercontent.com/1253785/34329465-473db662-e8f9-11e7-9e24-193e6ae04cfd.png">

**Comment by ryantstone** [comment]
I'm actually having the same issue. Setting either the accessibility label or identifier doesn't seem to help. When querying for static texts it can't seem to read the text label either.

**Comment by ryantstone** [comment]
@jmilillo I was finally able to access it via `app.otherElements["floaty"].children(matching: .other).element(boundBy: 4).tap()` The 4 in this case is the 4 element up from the bottom not including the floaty button.

**Comment by jmilillo** [comment]
@ryantstone Thank you for the hint.  It seems like we should be able to use the identifier directly, but I'll settle for a work around at this point.

**Comment by Nomad00** [comment]
I'm having issues accessing the button even with the accessibility values set. The approach @ryantstone mentions does not work for me either. Anyone explore this further?

**Comment by kciter** [comment]
Closing too old issue.
