### ISSUE TITLE
Floaty moves with keyboard only at first time, iOS 11

### ISSUE THREAD

**Issue by timqzm** [kciter/Floaty#170]
![2017-12-11-14 22 44](https://user-images.githubusercontent.com/13407092/33828927-18ae5f42-de7f-11e7-98a1-2074cc13b4ef.gif)

**Comment by timqzm** [comment]
I've made pull request https://github.com/kciter/Floaty/pull/171

**Comment by kciter** [comment]
Thank you :)

**Comment by nico75005** [comment]
Looks like the problem is still there (I'm on 4.0.1)
