### ISSUE TITLE
cant seem to add handlers to item that were custom added

### ISSUE THREAD

**Issue by Nick-Ace** [kciter/Floaty#174]
i added custom item to my floating button but i cant seem to handle the tap of each individual items in floating button

**Comment by leynercastillo** [comment]
Checking this issues https://github.com/kciter/Floaty/issues/97, i saw that the right way to set a handler to item is this:

`item.handler = { item in
      // Your handler, method or actions here
}`

I hope this helps someone else.

**Comment by SrdjanSpasojevic** [comment]
I'm having the same issue, I found that `touchesBegan` is not getting called at all. 

`item.handler = { item in
      // Your handler, method or actions here
}`

This is my usage of the handler.
