### ISSUE TITLE
Plus layer rotate out of button when using delegate to change button color

### ISSUE THREAD

**Issue by josephwong13** [kciter/Floaty#191]
Was trying to change the button color when the button is in open/close stage. I implement the two delegate methods like so:

    func floatyWillOpen(_ floaty: Floaty) {
            floaty.buttonColor = UIColor.init(red: 217, green: 217, blue: 217)
            floaty.setNeedsDisplay()
    }

    func floatyWillClose(_ floaty: Floaty) {
            floaty.buttonColor = UIColor.init(red: 0, green: 101, blue: 100)
            floaty.setNeedsDisplay()
    }

When clicking the button, the color did changed, but the "plus" was rotated out of the frame

<img width="79" alt="screen shot 2018-03-28 at 10 03 26 am" src="https://user-images.githubusercontent.com/15225843/38004545-4dfdedcc-326f-11e8-8595-71176cbcd85d.png">

Any solution for this?

**Comment by ShadowSynthesis** [comment]
Hi,

I have the same issue, Any ideas ?

**Comment by josephwong13** [comment]
I ended up using two custom images (plus and cross) to replace the plus sign, and change the image in the delegate methods. The rotation animation is gone though, which is kind of annoying.

    func floatyWillOpen(_ floaty: Floaty) , 
        floaty.buttonColor = UIColor.init(red: 217, green: 217, blue: 217)
        floaty.buttonImage = UIImage(named: "floaty_cross")
    }
    
    func floatyWillClose(_ floaty: Floaty) {
        floaty.buttonColor = UIColor.init(red: 0, green: 101, blue: 100)
        floaty.buttonImage = UIImage(named: "floaty_plus")
    }
