### ISSUE TITLE
Xcode 9.3 Error

### ISSUE THREAD

**Issue by musbaalbaki** [kciter/Floaty#193]
file:///... error: IB Designables: Failed to render and update auto layout status for ... (PPh-wN-vSV): dlopen(Floaty.framework, 1): no suitable image found.  Did find:
	Floaty.framework: required code signature missing for 'Floaty.framework'

**Comment by allaire** [comment]
I'm also seeing this, have you found a fix @musbaalbaki

**Comment by ilijapuaca** [comment]
This is actually an Xcode/Cocoapods issue (https://github.com/CocoaPods/CocoaPods/issues/7606).

Link to a comment that provides a working workaround: https://github.com/CocoaPods/CocoaPods/issues/7606#issuecomment-381279098
