### ISSUE TITLE
KCFloatingActionButton layout issue

### ISSUE THREAD

**Issue by zoufishanmehdi** [kciter/Floaty#195]
Hi, I'm getting the layout issue in the picture below. Is there any way to resolve this? 

![floatingbuttonbug](https://user-images.githubusercontent.com/12058032/38829274-8e91e926-4186-11e8-8f53-795fa6a20022.png)

Also, this might be an edge case but `KCFABOpened(_ fab: KCFloatingActionButton)` is getting called even when menu is open. In order to test edge cases and try to reproduce the issue above, I opened the menu, minimized the app and clicked on the menu again. Instead of closing the menu as the menu was already open, clicking on the menu created another layer of menu items on top of the previous menu items as `KCFABOpened(_ fab: KCFloatingActionButton)` was getting called rather than `KCFABClosed(_ fab: KCFloatingActionButton)`. Any ideas?

**Comment by akdsouza** [comment]
You might need to check the 'closed' property if its being set correctly in the lib, chances are that something is causing it to be set to true when you put the app in the background. A quick fix would be to subscribe to the didEnterBackground notification for you app and manually close the menu by calling the close() method on the fab.
