### ISSUE TITLE
How to use the library into Objective-C

### ISSUE THREAD

**Issue by nalancer08** [kciter/Floaty#202]
I trying to use the library into Objective-C, there is a way to do it? Dou you have some guide?

Thanks.

**Comment by ciccioska** [comment]
I have the same problem, have you finded a way?

**Comment by ciccioska** [comment]
Thank you for your answer, I just found this outdated objective-c alternative and I'm trying it.

**Comment by nalancer08** [comment]
@ciccioska Perfect 👍

**Comment by neoadventist** [comment]
@ciccioska did it work?
