### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by douglasfilipe** [kciter/Floaty#203]
Anyone can help me to fix it?
Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for FloatyViewController (BYZ-38-t0r): dlopen(Floaty.framework, 1): no suitable image found.  Did find:
	Floaty.framework: required code signature missing for 'Floaty.framework'

Swift 4.1
Floaty 4.0.1

**Comment by ilijapuaca** [comment]
This is actually an Xcode/Cocoapods issue (https://github.com/CocoaPods/CocoaPods/issues/7606).

Link to a comment that provides a working workaround: https://github.com/CocoaPods/CocoaPods/issues/7606#issuecomment-381279098

**Comment by douglasfilipe** [comment]
@ilijapuaca thanks so much! solved my problem
