### ISSUE TITLE
Floaty touch area bug.

### ISSUE THREAD

**Issue by Cyanide7523** [kciter/Floaty#206]
I used following code to make global floaty button's position more higher.

```Swift
override func viewDidLoad(){
    ...
    Floaty.global.button.paddingY += 48
    ...
```

global button's position got higher, but its actual touch area is still at global button's default position.

<img width="186" alt="2018-05-23 4 43 13" src="https://user-images.githubusercontent.com/25680715/40410483-e891a40e-5ea8-11e8-84b1-af6dbeb9225b.png">
<img width="186" alt="2018-05-23 4 43 13" src="https://user-images.githubusercontent.com/25680715/40410488-eb48e3ba-5ea8-11e8-8c53-2bd1097ccac8.png">

So when I touch that area, Floaty works as it touched, so I can't touch the tabBar button behind Floaty's touch area.

+++

I figured out floaty's touch area with checking color blended layers in Simulator

<img width="186" alt="2018-05-23 4 52 32" src="https://user-images.githubusercontent.com/25680715/40410896-d76d9b32-5ea9-11e8-8d30-e0395c7074a7.png">

**Comment by MussaCharles** [comment]
@Cyanide7523 Did you find a solution fo this issue?

**Comment by saurabh-amura** [comment]
Even I am facing this issue.

**Comment by MussaCharles** [comment]
Hi, @saurabh-amura 
I fixed the issue by disabling friendly tap like so: -
 myFloaty.friendlyTap = false

**Comment by ergunkocak** [comment]
I am experiencing the same issu after changing device orientation and hiding the tabbar on iPhone6+

**Comment by saurabh-selldo** [comment]
> Hi, @saurabh-amura
> I fixed the issue by disabling friendly tap like so: -
> myFloaty.friendlyTap = false

Hi @MussaCharles Thanks for the reply but that doesn't solve the issue on my end.
Could you share more settings which you applied to floaty object.
Here is my piece of code
`floaty.buttonColor = Colors.appNewColor`
`floaty.plusColor = UIColor.white`
`floaty.overlayColor = UIColor.black.withAlphaComponent(0.6)`
`floaty.paddingX = 12`
`floaty.paddingY = 12`
`floaty.friendlyTap = false`

**Comment by MussaCharles** [comment]
> > Hi, @saurabh-amura
> > I fixed the issue by disabling friendly tap like so: -
> > myFloaty.friendlyTap = false
> 
> Hi @MussaCharles Thanks for the reply but that doesn't solve the issue on my end.
> Could you share more settings which you applied to floaty object.
> Here is my piece of code
> `floaty.buttonColor = Colors.appNewColor`
> `floaty.plusColor = UIColor.white`
> `floaty.overlayColor = UIColor.black.withAlphaComponent(0.6)`
> `floaty.paddingX = 12`
> `floaty.paddingY = 12`
> `floaty.friendlyTap = false`


Hi, @saurabh-selldo  Sure here is my floaty view setttings, let me know if you need more info.

 let floatyButton: Floaty = {
        let view = Floaty()
        view.translatesAutoresizingMaskIntoConstraints = false
        view.plusColor = .white
        view.buttonColor = UIColor.green
        view.contentMode = .scaleAspectFill
        view.friendlyTap = false
        view.sticky = true
        view.backgroundColor = .clear
        return view
    }()
