### ISSUE TITLE
Floaty changing position itself when view appears

### ISSUE THREAD

**Issue by gulzatique** [kciter/Floaty#207]
please check my video to see the problem 👍 
https://youtu.be/GXUAQ9IgyJU

I tried to put the following code in viewdidappear and viewdidload and it still keeps jumping up and down
     

      floaty.paddingY = 59
        floaty.buttonColor = UIColor.floatyColor()
        floaty.fabDelegate = self
        floaty.buttonImage = #imageLiteral(resourceName: "ic_fab_add")
        floaty.size = 56
        view.addSubview(floaty)

what am I doing wrong or what should I add to the code or should modify it

thanks

**Comment by Mallinayudu** [comment]
I am facing same Problem

**Comment by gulzatique** [comment]
@Mallinayudu also you may find one option from vinayakparmar92 in here https://github.com/kciter/Floaty/issues/79  
I never tried it but the guy says it works

`floatyBtn.friendlyTap = false`

**Comment by naseeem** [comment]
try this YOURFLOATY.sticky = true

**Comment by augustocadini** [comment]
How I add View with Storyboard? The FAB button don't appears in the menu UIViews

**Comment by rehannali** [comment]
@gulzatique Have you find any solution.

**Comment by rehannali** [comment]
> How I add View with Storyboard? The FAB button don't appears in the menu UIViews

Just add simple view and assign class as Floaty.
