### ISSUE TITLE
remove all items from floaty

### ISSUE THREAD

**Issue by gulzatique** [kciter/Floaty#208]
how do I remove all items from floaty?

**Comment by gulzatique** [comment]
had to use this but if there is an easier way please let me know 

if floatyView.items.count != 0 {
            var i = 0
            while i <= floatyView.items.count {
                floatyView.removeItem(index: 0)
                i = i + 1
            }
        }

**Comment by josaal17** [comment]
let floaty = Floaty()
floaty.items.removeAll() //the library has that function

**Comment by gulzatique** [comment]
floaty.removeItem() does remove the item and also removes it from it's superview. 
removeAll() only removes items from array

@josaal17 correct me if I am wrong please
