### ISSUE TITLE
floaty items overlap when on swipe back

### ISSUE THREAD

**Issue by gulzatique** [kciter/Floaty#210]
I have a floaty button with 2 items. doing the following actions cause my problem to apper:
1) I tap on + button and it expands and shows 2 items
2) while it is being expanded I swipe slowly back and the problem shows, see screens below:

![photo_2018-06-01_16-08-07](https://user-images.githubusercontent.com/21258164/40835702-ff895652-65b5-11e8-92ab-114879d62107.jpg)

should be like so:
![photo_2018-06-01_16-08-03](https://user-images.githubusercontent.com/21258164/40835709-02d4e0ec-65b6-11e8-88b0-78baefd9bbb1.jpg)

**Comment by gulzatique** [comment]
for now aaded this to view did load and it worked: 

```
let gesture : UIScreenEdgePanGestureRecognizer = self.navigationController?.view.gestureRecognizers![0] as! UIScreenEdgePanGestureRecognizer
        gesture.addTarget(self, action: #selector (moved))
```


and this method: 
```
@objc private func moved() {
        floatyView.close()
    }
```

**Comment by darkbit34** [comment]
The same happens if the navigation bar changes size following a scroll that started before the button was opened!  Is there any way to put it back in place, I don't know for example with a Subviews layout without necessarily having to close it?
