### ISSUE TITLE
Glitch position iPhoneX

### ISSUE THREAD

**Issue by paulosaure** [kciter/Floaty#212]
Hello,

I used sample in my own project:

<img width="568" alt="capture d ecran 2018-06-11 a 11 37 19" src="https://user-images.githubusercontent.com/8981703/41224082-d472b676-6d6b-11e8-8bcc-3fd6a4f3b05e.png">

When I pushed the view controller with the floaty button configured in viewDidLoad, I see that the button is shifting upwards (on the baseline, which is different on iPhoneX).

![simulator-screen-shot---iphone-x---2018-06-11-at-11 32 32](https://user-images.githubusercontent.com/8981703/41223974-91104d76-6d6b-11e8-9276-25fc0bec729f.png)

Any solution ?
Thanks

**Comment by SheikhZayed** [comment]
@paulosaure 
as a quick fix you could try to manipulate the size like this 
`if UIDevice().userInterfaceIdiom == .phone {
            switch UIScreen.main.nativeBounds.height {
            case 1136:
                print("iPhone 5 or 5S or 5C")
            case 1334:
                print("iPhone 6/6S/7/8")
            case 1920, 2208:
                print("iPhone 6+/6S+/7+/8+")
            case 2436:
                print("iPhone X")

                
            default:
                print("unknown")
            }
        }`

**Comment by paulosaure** [comment]
Problem is not the size but the position ! I see the button shift upwards. Can I fix the position myself ?

**Comment by SheikhZayed** [comment]
@paulosaure 
its not about the size,you can manipulate your views x & y programatically like this 
   `yourView.view.frame = CGRect(x: 50, y: 30, width: yourView.view.frame.size.width, height: yourView.view.frame.size.height)`

**Comment by paulosaure** [comment]
@SheikhZayed 
Ok thanks. This solution works ;) !

**Comment by SheikhZayed** [comment]
@paulosaure glad it helped you,can u please help me in starting with it..im facing difficulty in setting it up ..
how do you use it in storyboard after adding pod ?

**Comment by paulosaure** [comment]
@SheikhZayed 
You should create a new topic ;) 

Anyway, I didn't use storyboard. In your view controller, you have to add it programmatically. 
Create it `var floaty = Floaty()` then add it in your view controller `viewController.view.addSubview(floaty)`.
No more complicated.

But I am not sur you can use storyboard. Personally I didn't try.

**Comment by SheikhZayed** [comment]
Thanks,let me try

**Comment by SheikhZayed** [comment]
@paulosaure could you please share your code which you used to manipulate the floaty view,im in a same situation and cannot get it worked

**Comment by SheikhZayed** [comment]
@paulosaure could you please share your code which you used to manipulate the floaty view,im in a same situation and cannot get it worked
