### ISSUE TITLE
How to change title background color

### ISSUE THREAD

**Issue by SheikhZayed** [kciter/Floaty#213]
is there a way to change the background color of item title?if not please let us in the new feature

**Comment by AndreVicenteW** [comment]
Did you find some way to do it? I don't use overlay, so a need do put a background in titles

**Comment by SheikhZayed** [comment]
@AndreVicenteW i found a way to do this,go to ur pods and then manually edit the FloatyItem.swift file.
i have also changed the title color and added the background to the title

**Comment by AndreVicenteW** [comment]
Thanks @SheikhZayed but i found another way.
In my file that I'm using the button I put

```
fab.items.forEach{ (item) in
    item.titleColor = UIColor.white
    item.titleLabel.backgroundColor = UIColor(red: 0, green: 0, blue: 0, alpha: 0.6)
    item.titleLabel.layer.cornerRadiur = 5
    item.titleLabel.frame.size.width = item.titleLabel.intrinsicContentSize.width + 10
    item.titleLabel.textAlignment = .center
    item.titleLabel.layer.masksToBounds = true
}
```

**Comment by SheikhZayed** [comment]
@AndreVicenteW great !

**Comment by chejarla-venkatesh** [comment]
@AndreVicenteW How did you make it work..? it is not woking for me. Can you please help me?

**Comment by chejarla-venkatesh** [comment]
I am a lil busy right now.. If you can, please send me any code snippet of
the ways or methods you tried and I will try to re implement them according
to your requirement.

Thank you.

**Comment by fayy92** [comment]
thank you for your reply
here are the codes :
        
floaty.addItem("Message", icon: UIImage(named: "message"))  { item in
            self.floaty.itemButtonColor = UIColor.green
        } 

floaty.addItem("Favorie", icon: UIImage(named: "star"))  { item in
            self.floaty.itemButtonColor = UIColor.blue   
        }

floaty.addItem("Flash", icon: UIImage(named: "heart"))  { item in
            self.floaty.itemButtonColor = UIColor.red    
        }


see also the attached photos


![sans titre](https://user-images.githubusercontent.com/43017688/45225986-145d7680-b2be-11e8-8101-e19759cf0177.jpeg)
![sans titre 4](https://user-images.githubusercontent.com/43017688/45225987-145d7680-b2be-11e8-969d-c7a5f20ddf40.jpeg)

**Comment by chejarla-venkatesh** [comment]
you are giving color in the completion handler of each button, it means
that you are giving the color when you press the button. The better way is
to create 3 custom FloatyItems with color, icon and title and add them to
your Floaty button..
I have just create a sample code, take a look:

import UIKit


class FloatyExercise: UIViewController {



    @IBOutlet weak var floaty: Floaty!



    override func viewDidLoad() {

        super.viewDidLoad()



        let fab1 = FloatyItem()

        fab1.buttonColor = .green

        fab1.icon =  imageLiteral(resourceName: "message")

        fab1.title = "Messages"

        let fab2 = FloatyItem()

        fab2.buttonColor = .blue

        fab2.icon =  imageLiteral(resourceName: "star")

        fab2.title = "Favories"

        let fab3 = FloatyItem()

        fab3.buttonColor = .red

        fab3.icon =  imageLiteral(resourceName: "heart")

        fab3.title = "Flashs"



        floaty.addItem(item: fab1)

        floaty.addItem(item: fab2)

        floaty.addItem(item: fab3)



    }

}

Output:
[image: Simulator Screen Shot - iPhone SE - 2018-09-10 at 10.56.00.png]

**Comment by chejarla-venkatesh** [comment]
Sorry for the late reply though. And one more thing I forget to mention in
the above piece of code is, How to make an action when an of the FlotyItem
buttons are tapped??
And for that try this below:

let fab1 = FloatyItem()

        fab1.buttonColor = .green

        fab1.icon =  imageLiteral(resourceName: "message")

        fab1.title = "Messages"

        fab1.handler = { fab1 in

            print("show messages")

        }

        let fab2 = FloatyItem()

        fab2.buttonColor = .blue

        fab2.icon =  imageLiteral(resourceName: "star")

        fab2.title = "Favories"

        fab2.handler = { fab2 in

            print("show Favories")

        }

        let fab3 = FloatyItem()

        fab3.buttonColor = .red

        fab3.icon =  imageLiteral(resourceName: "heart")

        fab3.title = "Flashs"

        fab3.handler = { fab3 in

            print("show Flashs")

        }



        floaty.addItem(item: fab1)

        floaty.addItem(item: fab2)

        floaty.addItem(item: fab3)

**Comment by chejarla-venkatesh** [comment]
@fayy92 Sorry for the late reply, you are giving color in the completion handler of each button, it means that you are giving the color when you press the button. The better way is to create 3 custom FloatyItems with color, icon and title and add them to your Floaty button..
I have just create a sample code, take a look:

    import UIKit

    class FloatyExercise: UIViewController {
    
    @IBOutlet weak var floaty: Floaty!
    
    override func viewDidLoad() {
        super.viewDidLoad()
     
        let fab1 = FloatyItem()
        fab1.buttonColor = .green
        fab1.icon =  imageLiteral(resourceName: "message")
        fab1.title = "Messages"

        let fab2 = FloatyItem()
        fab2.buttonColor = .blue
        fab2.icon =  imageLiteral(resourceName: "star")
        fab2.title = "Favories"

        let fab3 = FloatyItem()
        fab3.buttonColor = .red
        fab3.icon =  imageLiteral(resourceName: "heart")
        fab3.title = "Flashs"
   
        floaty.addItem(item: fab1)
        floaty.addItem(item: fab2)
        floaty.addItem(item: fab3)        
      }
    }

Output in the simulator: 
![simulator screen shot - iphone se - 2018-09-10 at 10 56 00](https://user-images.githubusercontent.com/25193620/45278898-b06cc500-b4ec-11e8-8355-fe6500130840.png)

**Comment by chejarla-venkatesh** [comment]
@fayy92 one more thing I forget to mention in the above piece of code is, How to make an action when an of the FlotyItem buttons are tapped??
And for that try this below:

    let fab1 = FloatyItem()
    fab1.buttonColor = .green
    fab1.icon =  imageLiteral(resourceName: "message")
    fab1.title = "Messages"
    fab1.handler = { fab1 in
            print("show messages")
        }    

    let fab2 = FloatyItem()
    fab2.buttonColor = .blue
    fab2.icon =  imageLiteral(resourceName: "star")
    fab2.title = "Favories"
    fab2.handler = { fab2 in
            print("show Favories")
        }    

    let fab3 = FloatyItem()
    fab3.buttonColor = .red
    fab3.icon =  imageLiteral(resourceName: "heart")
    fab3.title = "Flashs"
    fab3.handler = { fab3 in
            print("show Flashs")
        }    

    floaty.addItem(item: fab1)
    floaty.addItem(item: fab2)
    floaty.addItem(item: fab3)

**Comment by fayy92** [comment]
@chejarla-venkatesh thank you so much for your help, and also for the time spent to creationg this sample.
everything is OK ! :+1:  :1st_place_medal:  


![simulator screen shot - iphone 8 - 2018-09-10 at 16 54 12](https://user-images.githubusercontent.com/43017688/45305972-c180fa80-b51b-11e8-9489-fadf893d0f86.png)

**Comment by chejarla-venkatesh** [comment]
@fayy92 You are most welcome, and I'm happy that I could help. Happy coding..!
