### ISSUE TITLE
Floaty item customisation 

### ISSUE THREAD

**Issue by nitishmaropost** [kciter/Floaty#217]
I want something like this : 

<img width="154" alt="screen shot 2018-07-25 at 11 52 13 am" src="https://user-images.githubusercontent.com/37299932/43183052-54360d88-9001-11e8-9620-ab84dd6b622a.png">

Is this possible using your library ?

**Comment by akdsouza** [comment]
I don't think that's possible using the library, you will have to customise the appearance yourself. I had to implement something similar a while ago with rounded menu items and images on the right and had to provide the customisation myself through an extension. It's a bit of work but its possible.
