### ISSUE TITLE
How can I use one button using Floaty

### ISSUE THREAD

**Issue by dev-sawd** [kciter/Floaty#220]
I want one floating action button(no child button)
If it clicked, do something probably go to write message page

Is it possible?

**Comment by dannygrob** [comment]
use the delegate function: emptyFloatySelected() to catch the tap on an floaty button with no items added. Make sure to set the delegate.

`floaty.fabDelegate = self`

and implement:

```func emptyFloatySelected(_ floaty: Floaty) {

}```
