### ISSUE TITLE
change button color 

### ISSUE THREAD

**Issue by fayy92** [kciter/Floaty#227]
How can I add a color for each button, for example : red for  flashs, green for favories and blue for messages 
Thank you 

![sans titre 2](https://user-images.githubusercontent.com/43017688/45124977-c7b65600-b16c-11e8-9110-7e99e218732e.jpeg)
![sans titre 3](https://user-images.githubusercontent.com/43017688/45124982-d0a72780-b16c-11e8-998f-9664d3115383.jpeg)

**Comment by omima** [comment]
let item = FloatyItem()
  item.buttonColor = UIColor.blue
