### ISSUE TITLE
How to use Floaty on Storyboard?

### ISSUE THREAD

**Issue by augustocadini** [kciter/Floaty#228]
I'm have problems with different iPhones, in iPhone X for example the Floaty is cutted by TabBar, so I did try set constraint programatically, but this not works beucase errors about views hieararchy. In the samples the Floaty is not added by storyboard.

**Comment by yonlau** [comment]
Want to know that too!

**Comment by kot331107** [comment]
As I tried in Swift 4 xCode 9 : add an UIView to your UIViewController as usual. Then set it's Custom class as Floaty. then set it's constraints. It would show a floaty button in your UIViewController. 
there's an issue however: I can't see any Custom View attributes of floaty (color themes etc) in storyboard. Also xCode shows me an error in design mode "Failed to render and update auto layout status for UIViewController: dlopen (Floaty.framework) no suitable image found"

**Comment by yonlau** [comment]
Not only set custom class as Floaty in storyboard, set module to Floaty as well resolve my problem.

**Comment by kot331107** [comment]
@yonlau xCode should set module to Floaty itself, after you have selected your custom class...

**Comment by kot331107** [comment]
@rugmangathan likewise!  I had to set all attributes in code...

**Comment by carlosph816** [comment]
@rugmangathan i have the same problem any idea?
