### ISSUE TITLE
Support Xcode 10 and swift 4.2

### ISSUE THREAD

**Issue by SmolskyNeklo** [kciter/Floaty#231]

**Comment by kciter** [comment]
Updated 4.1.0
`pod "Floaty", "~> 4.1.0"`

**Comment by mohsinka** [comment]
I am using the same but still getting errors

**Comment by argentounce** [comment]
Tried both 4.1.0 tag and master branch and still not getting to compile

**Comment by andreififiita** [comment]
Is there a way to use a version for swift 4? if yes, what version?

**Comment by Natelegreat1** [comment]
I see that 4.1.0 is listed as a Release but the pod is not getting it without the explicit "~> 4.1.0"...

**Comment by mohsinka** [comment]
@Natelegreat1 unfortunately, despite using `pod "Floaty", "~> 4.1.0"` the code still isn't compilable.

**Comment by Natelegreat1** [comment]
@mohsinka By removing everything except **pod 'Floaty'**, it is now working for me with the Floaty Build Settings **Swift Language Version: Swift 4.2**!

**Comment by mohsinka** [comment]
@Natelegreat1 woah, nice.. still there were 3 more errors which i resolved easily.. thanks though 👍

**Comment by Natelegreat1** [comment]
@kciter this Issue can be closed :)

**Comment by stevenocean** [comment]
@Natelegreat1 I still get some errors when updated to 4.1.0,

Using Floaty (4.1.0)

error source code file: Floaty.swift : 355
error message: Type 'UIAccessibility.Notification' (aka 'UInt32') has no member 'layoutChanged'

**Comment by WinKhant-JLI** [comment]
> @mohsinka By removing everything except **pod 'Floaty'**, it is now working for me with the Floaty Build Settings **Swift Language Version: Swift 4.2**! I cleared DerivedData and re-built.

@Natelegreat1 It does not work for me even after changing to **pod 'Floaty'**
