### ISSUE TITLE
How do I correctly adding Floaty to a UITableViewController inside a UITabBarController?

### ISSUE THREAD

**Issue by andreififiita** [kciter/Floaty#237]
Hi, I am new to swift and IOs development and I am trying to add Floaty programmatically to my UITableViewController which is inside a UITabBarController. The issue is that the bottom tab bar is overlayed on top of the floating action button.

Inside my table view controller:

let floaty = Floaty()
...
self.view.addSubview(floaty)
// also tried: self.tabBarController?.view.addSubview(floaty)
I tried setting the margins like this:

floaty.layoutMargins = UIEdgeInsets(top: 0, left: 0, bottom: 60, right: 0)
floaty.layoutIfNeeded()
self.view.layoutIfNeeded()
But still it doesn't work.

The problem is that the bottom tab bar is overlaying the floating button because the position is relative to the bottom right corner of the window, not the table view.

**Comment by jagathprasanga** [comment]
Im also having same issue, Please help.

**Comment by Sargis** [comment]
actionButton = JJFloatingActionButton.init(frame: CGRect(x: self.view.bounds.width/2 - 30, y: self.view.bounds.height  - 55 - bottomHeight, width: 60, height: 60))

        actionButton.buttonImage = #imageLiteral(resourceName: "imgPlaceHolderLogo")
        actionButton.buttonColor = #colorLiteral(red: 0.1098039216, green: 0.09019607843, blue: 0.231372549, alpha: 1)
        actionButton.itemAnimationConfiguration = .circularPopUp(withRadius: 60)
        actionButton.buttonAnimationConfiguration = .rotation(toAngle: .pi)

        actionButton.buttonAnimationConfiguration.opening.duration = 0.8
        actionButton.buttonAnimationConfiguration.closing.duration = 0.6

        
        actionButton.addItem(title: nil, image: UIImage(named: "soccer-1")) { item in
            // do something
        }
        
        actionButton.addItem(title:nil, image: UIImage(named: "Basketball-1")) { item in
            // do something
        }
        view.addSubview(actionButton)





override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        self.view.bringSubviewToFront(self.actionButton)
    }

**Comment by gzattaraML** [comment]
You can set the Floaty paddingY attribute after instantiation:

```  
let floaty = Floaty()
floaty.paddingY = 54
floaty.addItem("Hello, World!", icon: UIImage(named: "icon")!)
view.addSubview(floaty)
```

Ideally you would add the tab bar height to the already set padding (14)

**Comment by saurabh-amura** [comment]
@gzattaraML PaddingY doesn't work as expected.
It places the floaty button wherever we want. But when we tap on tab bar, the floaty button gets tapped.
![Screenshot 2019-05-06 at 11 55 37 AM](https://user-images.githubusercontent.com/43401664/57209337-e7509780-6ff5-11e9-8e1e-d55d34369c4d.png)

**Comment by Ali-Aqdas** [comment]
> You can set the Floaty paddingY attribute after instantiation:
> 
> ```
> let floaty = Floaty()
> floaty.paddingY = 54
> floaty.addItem("Hello, World!", icon: UIImage(named: "icon")!)
> view.addSubview(floaty)
> ```
> 
> Ideally you would add the tab bar height to the already set padding (14)

thanks for ur reply its worked for me

**Comment by gzattaraML** [comment]
> @gzattaraML PaddingY doesn't work as expected.
> It places the floaty button wherever we want. But when we tap on tab bar, the floaty button gets tapped.
> ![Screenshot 2019-05-06 at 11 55 37 AM](https://user-images.githubusercontent.com/43401664/57209337-e7509780-6ff5-11e9-8e1e-d55d34369c4d.png)

You are right, it places the button with a different padding but the frame is getting larger instead of moving to the right place. Didn't notice it because I'm placing the button right on top of the tab bar. In the other hand I bet you are placing your Floaty button on top of the tab bar, that's why you get it tapped instead of it.

I will take a look on the frame issue to see if there is a workaround, `draw` method, that seems to be a good approach to solve the button position issue, isn't working for me

**Comment by gzattaraML** [comment]
@saurabh-amura set `floaty.friendlyTap = false` and you should be good to go, the frame stuff is done it on purpose but luckily it is configurable.

**Comment by saurabh-amura** [comment]
> > @gzattaraML PaddingY doesn't work as expected.
> > It places the floaty button wherever we want. But when we tap on tab bar, the floaty button gets tapped.
> > ![Screenshot 2019-05-06 at 11 55 37 AM](https://user-images.githubusercontent.com/43401664/57209337-e7509780-6ff5-11e9-8e1e-d55d34369c4d.png)
> 
> You are right, it places the button with a different padding but the frame is getting larger instead of moving to the right place. Didn't notice it because I'm placing the button right on top of the tab bar. In the other hand I bet you are placing your Floaty button on top of the tab bar, that's why you get it tapped instead of it.
> 
> I will take a look on the frame issue to see if there is a workaround, `draw` method, that seems to be a good approach to solve the button position issue, isn't working for me

I believe that for now it is easy to embed tableview in a UIView and add floaty button to this superview of tableview.

**Comment by mkornyev** [comment]
Setting the paddingX/paddingY attributes doesn't seem to do anything.

Can anyone help?
