### ISSUE TITLE
How set FAB to top right ?

### ISSUE THREAD

**Issue by Maxwell6635** [kciter/Floaty#238]
I unable to use floaty in storyboard, now i use code to add subview, how to make the floaty is at the top right of the parent view?

**Comment by kciter** [comment]
It's impossible now.

**Comment by utsavDave97** [comment]
`swift 
var fabButton = Floaty(frame: CGRect(x: UIScreen.main.bounds.size.width - 60,y: 30,width: 40,height: 40))
`

This would the fab button at top right
