### ISSUE TITLE
Add background view behind item title

### ISSUE THREAD

**Issue by zoufishanmehdi** [kciter/Floaty#244]
Hi, I would like to add a white background view behind item title like the one displayed in the image to make the item title standout. Is it possible to do that? Thank you!

<img width="335" alt="screen shot 2018-12-06 at 11 31 54 am" src="https://user-images.githubusercontent.com/12058032/49597579-bdae1a00-f94a-11e8-977e-5ec6170d15bc.png">

**Comment by mojtaba-almoussawi** [comment]
Hi , is there a way to add it?
