### ISSUE TITLE
plusLayer has wrong position when using with bottom bar

### ISSUE THREAD

**Issue by rbresjer** [kciter/Floaty#252]
### Steps to reproduce

1. Create a UITabBarController with two child UIViewControllers
2. Add a Floaty with an item to the first child UIVIewControllers
3. Run the app
4. Open/expand the Floaty
5. Switch to the other UIVIewController
6. Switch back to the UIVIewController with the Floaty

### Expected behaviour
The Floaty looks normal, like it looked before you switched tabs.

### Actual behaviour
The X-button (plusLayer) is offset incorrectly:

<img width="78" alt="screenshot 2019-02-19 at 16 22 04" src="https://user-images.githubusercontent.com/11976380/53026081-87b90600-3462-11e9-9036-7c5615d8fe95.png">

### Workaround
Close the Floaty on viewWillDisappear, e.g.:
```
override func viewWillDisappear(_ animated: Bool) {
  floaty.close()
  super.viewWillDisappear(animated)
}
```

**Comment by weakfl** [comment]
`4.1.0` has the same issue, so I don't think this is related to #250.

**Comment by RajvinderPayU** [comment]
is it fixed?

**Comment by weakfl** [comment]
> is it fixed?

@RajvinderPayU it's fixed in master.

@kciter Maybe you could provide provide a new release including this bugfix?
