### ISSUE TITLE
Floaty only in ViewController, but black overlay above tabor and NavBarHeightLargeState

### ISSUE THREAD

**Issue by psredzinski** [kciter/Floaty#256]
How can I make black semi-transparent overlay to be on top on nav and tab bar, while having floaty button only in a single controller?

**Comment by FidelHen** [comment]
UIApplication.shared.keyWindow!.addSubview(fab)
        UIApplication.shared.keyWindow!.bringSubviewToFront(fab)

**Comment by arishanapalli** [comment]
What is fab? Where you changing this value 
I added  plusButton via storyboard. 
 @IBOutlet weak var plusButton: Floaty!
