### ISSUE TITLE
Support Swift 5

### ISSUE THREAD

**Issue by ascentman** [kciter/Floaty#259]
**Environment**

Xcode Version: 10.2
Swift Version: 5

**Goals**
Swift 5 support for the framework

**Expected Results**
No warning to convert Floaty to Swift 5

**Actual Results**
Xcode created warnings to convert Floaty to Swift 5

**Steps to Reproduce**
Build the cocoapod in Xcode 10.2

**Code Samples & Details**
Run any project depending on the pod's in Xcode 10.2 to see the warning.

**Comment by Drwalcore** [comment]
+1

**Comment by kciter** [comment]
updated 4.2.0
