### ISSUE TITLE
items sometimes does not display when using Swift 5

### ISSUE THREAD

**Issue by samkim102** [kciter/Floaty#267]
We're opening the menu using `popAnimationWithOpen` expecting the following:

![What should happen](https://user-images.githubusercontent.com/8174249/63204664-2ef6bd00-c0d5-11e9-9ada-e77d42d5adee.png)

it works fine when we're using Swift 4.2, but when we switch over to Swift 5, this _sometimes_ happens:

![What occasionally happens](https://user-images.githubusercontent.com/8174249/63204665-2ef6bd00-c0d5-11e9-8c54-56abffe7aa15.png)

We have tried compiling with Xcode 11 beta but this still happens.  I would appreciate some insight.

**Comment by samkim102** [comment]
FYI: using latest commit from `master` branch (commit hash: `0048439dc3f0180fa2dd361583fe54bdba3c711f`)

**Comment by HadiYaac** [comment]
@samkim102 What was the solution? Still having the problem. Even using the latest version 4.2.0
