### ISSUE TITLE
button moved out of position when dismiss a modal view controller in iOS 13

### ISSUE THREAD

**Issue by kjoe07** [kciter/Floaty#275]
let tabBarHeight = tabBar.layer.bounds.height * 1.2
        let win: UIWindow = ((UIApplication.shared.delegate?.window)!)!
         let button = Floaty(frame: CGRect(origin: CGPoint(x: 0.0, y: win.frame.size.height),size: CGSize(width: tabBarHeight, height: tabBarHeight)))
         button.center = CGPoint(x: win.center.x, y: win.frame.size.height - tabBar.layer.bounds.height)
         button.buttonImage = UIImage(named: "icoZ")
        button.tag = 52
        button.backgroundColor = UIColor(named: "Buttongreen")
        button.layer.borderWidth = 0
        let item = FloatyItem()
        item.buttonColor = UIColor(named: "ButtonGreen") ?? UIColor.green
        item.iconImageView.image = #imageLiteral(resourceName: "percentButton")
        item.handler = { item in
            let vc = self.storyboard?.instantiateViewController(withIdentifier: "PercentVC") ?? PercentViewController()
            DispatchQueue.main.async {
                self.present(vc, animated: true, completion: nil)
                button.close()
            }
        }
        button.addItem(item: item)
        let item2 = FloatyItem()
        item2.buttonColor = UIColor(named: "ButtonGreen") ?? UIColor.green
        item2.iconImageView.image = #imageLiteral(resourceName: "scanQr")
        item2.handler = { item in
            let vc = ScannerViewController()
           DispatchQueue.main.async {
               self.present(vc, animated: true, completion: nil)
               button.close()
           }
        }
        button.addItem(item: item2)
        self.view.addSubview(button)
        button.translatesAutoresizingMaskIntoConstraints = false
        let bottom = button.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: -15)
        let center = button.centerXAnchor.constraint(equalTo: view.centerXAnchor)
        let height = button.heightAnchor.constraint(equalToConstant: tabBarHeight)
        let width = button.widthAnchor.constraint(equalToConstant: tabBarHeight)
        NSLayoutConstraint.activate([bottom,center,height,width])
created the button like this in the TababarController class. when open the tabby is shown correctly, when a modal presentation is done and dismiss 
and is shown like this.
![IMG_4323](https://user-images.githubusercontent.com/3653060/70471897-1a7f6b80-1a9c-11ea-9b4c-69eaf44da1dd.PNG)
this is how is shown.
![IMG_E4324](https://user-images.githubusercontent.com/3653060/70471915-266b2d80-1a9c-11ea-9149-b76652ccba07.JPG)

**Comment by rommank** [comment]
Try to move 
`self.view.addSubview(button) `
right under 
`let button = Floaty(frame: CGRect(origin: CGPoint(x: 0.0, y: win.frame.size.height),size: CGSize(width: tabBarHeight, height: tabBarHeight)))`

It sounds weird but that might help;)

**Comment by GigabyteTheOne** [comment]
Yeah, same for me.
Had to use `UIAdaptivePresentationControllerDelegate.presentationControllerWillDismiss()` to update button layout.

**Comment by alfredolucomav** [comment]
HI @GigabyteTheOne,

I'm tried to do the same as you do but it stills does not working. My code is the following:

```
self.dismiss(animated: true, completion: {
            guard let presentation = self.presentationController else { return }
            if #available(iOS 13.0, *) {
                presentation.delegate?.presentationControllerWillDismiss?(presentation)
            } else {
                // Fallback on earlier versions
            }
        })
```

Am I doing it correctly?

Best Regards

**Comment by GigabyteTheOne** [comment]
Hi @alfredolucomav,

Firstly I've been setting my ViewController as a delegate and doing this:
```
extension ViewController: UIAdaptivePresentationControllerDelegate {
    func presentationControllerWillDismiss(_ presentationController: UIPresentationController) {
        floatyButton.superview?.layoutIfNeeded()
    }
}
```

But then I found that my problem was in another place and I just needed to set 
```
floatyButton.respondsToKeyboard = false
```

**Comment by alfredolucomav** [comment]
Hi @GigabyteTheOne ,

That works like a charm! `floatyButton.respondsToKeyboard = false`

Thanks a lot!
Best Regards
