### ISSUE TITLE
Make Background frame to be set on whole screen, & on tapping anywhere close the fab button.

### ISSUE THREAD

**Issue by sakshiGoel26** [kciter/Floaty#33]
Hello,

I want the background layer to be covered on whole screen on my view, i.e above navigationBar & TabBarController, & on tap of this layer float button should be closed.

For this in "KCFloatingActionButton" class, I added my own ImageView instead of adding overlayLayer, & integrated TapGesture on it. But tap gesture is not working on click of it, its taking that tap gesture functionality around plus button, also image view is not covering my navigation bar.

**Comment by justinium** [comment]
@sakshiGoel26 Did you find a solution to this?

**Comment by sakshiGoel26** [comment]
@justinium , yes I added a view with its alpha set to 0.7 on window, & it solved my purpose.
