### ISSUE TITLE
Adding buttons of other type!

### ISSUE THREAD

**Issue by Dershowitz011** [kciter/Floaty#36]
If you could make it possible for us to add any button to the list of buttons. It'd be amazing.

**Comment by kciter** [comment]
What do you mean? I don't understand what you are saying.

**Comment by Dershowitz011** [comment]
@kciter [ActionButtonItems] doesn't take any other buttons except of the type ActionButtonItems. So if you could do something where other buttons can be casted as ActionButtonItem and added to the list, it'd be really good.
