### ISSUE TITLE
Fab falls apart when I open control center

### ISSUE THREAD

**Issue by alexrodrigues** [kciter/Floaty#62]
![fab evidence](https://cloud.githubusercontent.com/assets/5357919/18024634/91324a4a-6be5-11e6-82a4-91e09aff96fb.png)

When I open the Fab menu and then open the "control center" the whole menu falls apart.

**Comment by kciter** [comment]
Hello @alexrodrigues 
I can't reproduce. 😢 
Please tell me the situation more closely.

**Comment by iAviatorJose** [comment]
@alexrodrigues  @kciter  i am experiencing the same problem.
i Used Storyboard to set up my fab Button
I got i when i do the following.
-> open fab Menu 
-> click on a child fab MenuItem 
-> navigate to a screen where i have UITextField, i click on it keyboard open 
-> press back on UINavigationBar.
-> Now the fab moves up to half of the screen.
-> click on the fab -> fab menu opens up 
-> click again to close -> NOW THE MENUS COLLAPSES AS SHOWN IN IMAGE BY ALEX.

**Comment by iAviatorJose** [comment]
One more Problem.
I have screen where i have a UITableview and Fab.
Here i try add programmatically to add fab button.
The Fab is not showing while running.
ON UI Debugging it, i came to know that fab get hidden behind tableview

**Comment by iAviatorJose** [comment]
@kciter  @alexrodrigues  did you guys find any solution or work around for this.

**Comment by alexrodrigues** [comment]
Hi @iAviatorJose, I didn't found any solution. :(

**Comment by alexrodrigues** [comment]
@kciter Just turn around your device (Landscape left for example) and you will notice fab all messed up.

**Comment by iAviatorJose** [comment]
@kciter  any updates regarding this issue.

**Comment by kciter** [comment]
Hello,
I had forgotten to read the issue. I will update soon.

**Comment by iAviatorJose** [comment]
@kciter did you find any solution to this problem
