### ISSUE TITLE
Action Button change position when keyboard shows

### ISSUE THREAD

**Issue by shieer** [kciter/Floaty#76]

**Comment by burakkilic** [comment]
I have the same problem. I position the button in the middle of the page, but when keyboard appears, it moves down. How can I stop that?

**Comment by sachithamadhupa** [comment]
https://github.com/kciter/KCFloatingActionButton/issues/79

**Comment by sachithamadhupa** [comment]
check this:https://github.com/kciter/KCFloatingActionButton/issues/79

**Comment by Harshit31** [comment]
just set sticky property to true
