### ISSUE TITLE
overlay covers navigation bar

### ISSUE THREAD

**Issue by StevenArmandLee** [kciter/Floaty#77]
I'm wondering if we can make the overlay to covers all the screen including the navigation bar?

**Comment by Tiago-Rocha** [comment]
Any updates on this? Facing the same issue here.

**Comment by StevenArmandLee** [comment]
@Tiago-Rocha no luck man, but I'm thinking to add my own when the fap is open.

if you can solve this, please let me know

**Comment by Tiago-Rocha** [comment]
@StevenArmandLee , my workaround was the follow (I have both tabbar and navigation controller):

I am extending my ViewController to the delegate KCFloatingActionButtonDelegate
and on KCFABOpened() 
yourtabbar.layer.zPosition = -1
on KCFABOpened() 
yourtabbar.layer.zPosition = 0
(This solved my problem on the tabbar, but not on the navigation controller)

As for the Navigation Controller:
* Changed zPosition of Nav Controller (didn't solve it)
* (Workaround) -> Added a layer same size of the nav controller, played with hidden property

My code below:
extension TimelineViewController: KCFloatingActionButtonDelegate {
    
    func KCFABOpened(fab: KCFloatingActionButton) {
        self.overlayNavBar.hidden = false
        self.tabBarController?.tabBar.layer.zPosition = -1
        self.tabBarController?.tabBar.userInteractionEnabled = false
        self.navigationController?.navigationBar.layer.zPosition = -1
        self.overlayNavBar.layer.zPosition = 0
    }
    func KCFABClosed(fab: KCFloatingActionButton) {
        self.tabBarController?.tabBar.layer.zPosition = 0
        self.tabBarController?.tabBar.userInteractionEnabled = true
        self.navigationController?.navigationBar.layer.zPosition = 0
        self.overlayNavBar.layer.zPosition = -1
        self.overlayNavBar.hidden = true
    }

**Comment by StevenArmandLee** [comment]
@Tiago-Rocha thanks for the help mate, but im worndering if you could give me what is the type of overlaynavbar and the properties that you set on it

thanks.

**Comment by Tiago-Rocha** [comment]
@StevenArmandLee sure here it goes.

Declare the view as a variable of the controller
let overlayNavBar = UIView()

On viewDidAppear define the aspect (personal color, size = nav controller, position on screen, hidden and zPosition) of the view.
//Setting Overlay View for Nav Bar
        self.overlayNavBar.backgroundColor = PetableColors.FABOverlay
        self.overlayNavBar.frame = CGRect(x: 0, y: -20, width: self.navigationController!.navigationBar.frame.width, height: self.navigationController!.navigationBar.frame.height + 20)
        self.navigationController?.navigationBar.addSubview(self.overlayNavBar)
        self.overlayNavBar.layer.zPosition = -1
        self.overlayNavBar.hidden = true

Then the FAB delegate takes care of the rest. 

Hope it helps!

**Comment by jettandres** [comment]
It took me quite some time overthinking about it. The simple solution is to add your FAB as a subview to your Navigation Controller.

`self.navigationController!.view.addSubview(fab);`

**Comment by andreififiita** [comment]
@jettandres  this only works partially for me: for instance, when first loading the app, everything is ok, then after switching to another tab it is still positioned under the tab bar. 
I added a post here: 
https://stackoverflow.com/questions/52930000/adding-float-action-button-to-a-view-controller-inside-tab-bar-controller
