### ISSUE TITLE
Changing the button image in an item handler stop the animation

### ISSUE THREAD

**Issue by nico75005** [kciter/Floaty#97]
I have a button with several items.

One of them is created this way:

```
sortButton.addItem("Time", icon: #imageLiteral(resourceName: "clockwise").withColor(.red)) { [weak self] _ in 
	self?.tableView.orderBy(.time)
	self?.sortButton.buttonImage = #imageLiteral(resourceName: "clockwise").withSize(CGSize(width: 25, height: 25))?.withColor(.red)
	self?.sortButton.buttonColor = .white
}
```

The problem is that changing the `buttonImage` inside the `handler` stop the animation and create for like a second (probably the time of the animation) some glitches in the display as you can see here:

![bug](https://cloud.githubusercontent.com/assets/1647328/23331281/908b43d6-fbc7-11e6-9a99-6ac41c775b1e.png)

Is there anyway to fix this or is there a better way to change the image of the button when an item is selected?

Cheers

**Comment by adopesua** [comment]
i solved this problem doing this:
//1 declare variable
`var addButton = KCFloatingActionButton()`

//2 In view did appear, print button (I create in viewdidappear because this pod have bug when keyboard appears in same view controller and another child view controller).
`override func viewDidAppear(animated: Bool) {
        printButton()
    }`

//3 printButton
`
func printButton() {
        addButton.removeFromSuperview()
        addButton = KCFloatingActionButton()

        let item = KCFloatingActionButtonItem()
        item.buttonColor = UIColor(netHex: 0x3BB3C2)
        item.icon = UIImage(named: "ic_add")
        item.circleShadowColor = UIColor.blackColor()
        item.titleShadowColor = UIColor.blackColor()
        item.title = "Button title 1"
        item.handler = { item in
            //call function
        }
        
        let item2 = KCFloatingActionButtonItem()
        item2.buttonColor = UIColor(netHex: 0xFF3C38)
        item2.icon = UIImage(named: "ic_edition.png")
        item2.circleShadowColor = UIColor.blackColor()
        item2.titleShadowColor = UIColor.blackColor()
        item2.title = "Button title 2"
        item2.handler = { item in
            //Call function
        }
        
        let item3 = KCFloatingActionButtonItem()
        item3.buttonColor = UIColor(netHex: 0xFF3C38)
        item3.icon = UIImage(named: "ic_trash.png")
        item3.circleShadowColor = UIColor.blackColor()
        item3.titleShadowColor = UIColor.blackColor()
        item3.title = "Button title 3"
        item3.handler = { item in
            /Call function
        }
        
        addButton.addItem(item: item3)
        addButton.addItem(item: item2)
        addButton.addItem(item: item)
        addButton.fabDelegate = self
        addButton.buttonColor = UIColor(netHex: 0xFF3C38)
        addButton.plusColor = UIColor.whiteColor()
        
        self.view.addSubview(addButton)
        
    }`
