### ISSUE TITLE
When using two buttons, they are sometimes both expandable at the same time

### ISSUE THREAD

**Issue by nico75005** [kciter/Floaty#98]
I have two buttons.

I go in my view controller, tap on one of them, close the menu (by tapping on one of the items or on the background), then tap on the other one. 

And there I end up with the other button I can activate without the first one disappearing:

<img width="160" alt="screen shot 2017-02-26 at 02 11 17" src="https://cloud.githubusercontent.com/assets/1647328/23331349/e400b54a-fbc8-11e6-8892-bfa3ec51c629.png">

<img width="162" alt="screen shot 2017-02-26 at 02 06 16" src="https://cloud.githubusercontent.com/assets/1647328/23331345/c1a60720-fbc8-11e6-84fa-789e94cc4350.png">

<img width="210" alt="screen shot 2017-02-26 at 02 10 42" src="https://cloud.githubusercontent.com/assets/1647328/23331347/cbf119a4-fbc8-11e6-8824-073bf42c8964.png">

This is how I setup my buttons:

```
sortButton.buttonImage = #imageLiteral(resourceName: "order").withSize(CGSize(width: 25, height: 25))?.withColor(.white)
sortButton.buttonColor = .mainRed
sortButton.itemButtonColor = .white
sortButton.overlayColor = UIColor.black.withAlphaComponent(0.8)
sortButton.rotationDegrees = -90
sortButton.friendlyTap = false
```

Is it a bug or is there a way to avoid that?

Thanks

**Comment by kciter** [comment]
You can use `friendlyTap`
refs: #60, #47

**Comment by nico75005** [comment]
Even with `friendlyTap = true` it doesn't work.

**Comment by kciter** [comment]
Please assign `false`. 
`friendlyTap = false` :)

**Comment by nico75005** [comment]
Whether I use `true` or `false` or both buttons it doesn't work.

**Comment by kciter** [comment]
I will check it.
